services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine3.17
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: hng

    networks:
      - app-nets

  app:
    container_name: hng-stage-2
    build: .
    image: hng-stage-2:v1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8080:8080'
    networks:
      - app-nets

networks:
  app-nets:
    driver: bridge